version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: buildpack-deps:trusty
    parallelism: 3
    branches:
      only:
        - dev
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: npm run build
      - run: git push heroku master
    staging:
      branch: master
      heroku:
        appname: react-test-ci

