version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      only:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: npm run build
  steps:
    - checkout
    - run:
        name: Deploy Master to Heroku
        command: |
          git push https://heroku:d4f9d9c1-01a7-484b-9256-7fecb28606fd@git.heroku.com/react-test-ci.git master
