version: 0.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    parallelism: 3
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: ls
      - run: npm run build