version: 0.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    parallelism: 3
    resource_class: large
    branches:
      only:
        - master
    steps:
      - run: rm -rf ./node_modules
      - run: npm i
      - run: ls
      - run: npm run build