version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      ignore:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: npm run build

