version: 0.17
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      only:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: npm run build
      - heroku/deploy-via-git