version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      only:
        - dev
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: rm -rf ./build
      - run: rm -rf ./package-lock.json
      - run: npm i
      - run: npm run build
      - run: git checkout master
      - run: git commit -am "deploy"
      - run: git push origin master
    staging:
      branch: master
      heroku:
        appname: react-test-ci

