version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      only:
        - master
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: npm i
      - run: npm run build
    deployment:
      staging:
        branch: master
        heroku:
          appname: react-test-ci

