version: 0.20

jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 3
    branches:
      only:
        - dev
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: rm -rf ./node_modules
      - run: rm -rf ./build
      - run: rm -rf ./package-lock.json
      - run: npm i
      - run: npm run build
      - run: git checkout master
      - run: git config --global user.email "stoler@ya.ru"
      - run: git config --global user.name "stoler"
      - run: git commit -am "deploy"
      - run: |
          git push https://heroku:d4f9d9c1-01a7-484b-9256-7fecb28606fd@git.heroku.com/react-test-ci.git master
    staging:
      branch: master
      heroku:
        appname: react-test-ci

