version: 0.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    parallelism: 3
    resource_class: large
    branches:
      only:
        - master
    steps:
      - run: npm run start